input_size: !!python/tuple
- 28
- 28
learning_rate: 0.01
model_channels:
- !!python/tuple
  - 1
  - 64
- !!python/tuple
  - 64
  - 64
- !!python/tuple
  - 64
  - 128
num_classes: 10
strides:
- 1
- 1
- 2
