wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.5
    cli_version: 0.18.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729777041
    t:
      1:
      - 1
      - 55
      - 106
      3:
      - 4
      - 23
      - 42
      - 55
      4: 3.12.5
      5: 0.18.5
      8:
      - 5
      13: linux-x86_64
